---
title: "FARS"
author: "Priyojit Das"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
#### fars_read

Read Fatality Analysis Reporting System data from csv file
 
This function reads data from a .csv file, where the name of the file is supplied as the argument of the function.
If file does not exist in the current working directory, then the function will give error.

Input : filename A character string which is the name of the file

Output : This function returns a data frame

Examples : 
fars_read(filename = "accident_2014.csv.bz2")
```
fars_read <- function(filename) {
        if(!file.exists(filename))
                stop("file '", filename, "' does not exist")
        data <- suppressMessages({
                readr::read_csv(filename, progress = FALSE)
        })
        dplyr::tbl_df(data)
}
```
#### make_filename

Create filename from a given particular year
 
This function creates a filename for a particular year, which can be modified in
the code by changing \code{year}
 
Input : year A integer which depicts the year
 
Output : This function returns a charcter string which is the name of the file
 
Examples : 
make_filename(year = 2014)
```
make_filename <- function(year) {
        year <- as.integer(year)
        sprintf("accident_%d.csv.bz2", year)
}
```
#### fars_read_years

Return a dataframe which contains year and month column for a set of years
 
This function creates a dataframe for a set of years, which can be modified in
the code by changing years.
If the dataset does not conatin the given year, then it will give warning
 
Input : years A list/vector containing years
 
Output : This function returns a dataframe which contains two columns, month and year
 
Examples : 
fars_read_years(years = c(2013,2014,2015))
```
fars_read_years <- function(years) {
        lapply(years, function(year) {
                file <- make_filename(year)
                tryCatch({
                        dat <- fars_read(file)
                        dplyr::mutate(dat, year = year) %>% 
                                dplyr::select(MONTH, year)
                }, error = function(e) {
                        warning("invalid year: ", year)
                        return(NULL)
                })
        })
}
```
#### fars_summarize_years

Return a dataframe which contains year and corresponding total entries, group by year and month
 
This function creates a dataframe for a set of years, which can be modified in
the code by changing \code{year}
 
Input : years A list/vector containing years
 
Output : This function returns a dataframe which contains year and corresponding 
total entries, group by year and month
 
Examples : 
fars_summarize_years(years = c(2013,2014,2015))
```
fars_summarize_years <- function(years) {
        dat_list <- fars_read_years(years)
        dplyr::bind_rows(dat_list) %>% 
                dplyr::group_by(year, MONTH) %>% 
                dplyr::summarize(n = n()) %>%
                tidyr::spread(year, n)
}
```
#### fars_map_state

Plot a maps where the no of accidents are plotted on the state
 
This function generates a maps where the no of accidents are plotted on the 
state\code{year}

If wrong state code is given, then it will raise error
 
Input : state.num A integer id of a state, year A integer which depicts the year
 
Examples : 
fars_map_state(state.num = 12, year = 2014)
```
fars_map_state <- function(state.num, year) {
        filename <- make_filename(year)
        data <- fars_read(filename)
        state.num <- as.integer(state.num)

        if(!(state.num %in% unique(data$STATE)))
                stop("invalid STATE number: ", state.num)
        data.sub <- dplyr::filter(data, STATE == state.num)
        if(nrow(data.sub) == 0L) {
                message("no accidents to plot")
                return(invisible(NULL))
        }
        is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
        is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
        with(data.sub, {
                maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
                          xlim = range(LONGITUD, na.rm = TRUE))
                graphics::points(LONGITUD, LATITUDE, pch = 46)
        })
}
```
